version: '3.1'
services:
  api-gtw:
    image: api-gtw:latest
    container_name: api-gtw
    ports:
      - '8080:8080'
    depends_on:
      - auth-svc
    networks:
      - auth-svc
  auth-svc:
    image: auth-svc:latest
    container_name: auth-svc
    depends_on:
      - postgres
      - redis
    networks:
      - auth-svc
      - postgres
      - redis
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - redis
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - postgres

networks:
  auth-svc:
  redis:
  postgres: